version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./config:/app/config

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"